all:
	g++ -std=c++11 -I../ test_array_default_constructor.cpp -o test_array_default_constructor
	g++ -std=c++11 -I../ test_array_constructor_with_initializer_list.cpp -o test_array_constructor_with_initializer_list
	g++ -std=c++11 -I../ test_array_size.cpp -o test_array_size
	g++ -std=c++11 -I../ test_array_empty.cpp -o test_array_empty
	g++ -std=c++11 -I../ test_array_operator[].cpp -o test_array_operator[]
	g++ -std=c++11 -I../ test_array_front.cpp -o test_array_front
	g++ -std=c++11 -I../ test_array_back.cpp -o test_array_back
	g++ -std=c++11 -I../ test_array_data.cpp -o test_array_data
	g++ -std=c++11 -I../ test_array_fill.cpp -o test_array_fill
	g++ -std=c++11 -I../ test_array_swap.cpp -o test_array_swap
	g++ -std=c++11 -I../ test_array_iterator.cpp -o test_array_iterator
        
clean:
	rm -rf test_array_default_constructor
	rm -rf test_array_constructor_with_initializer_list
	rm -rf test_array_size
	rm -rf test_array_empty
	rm -rf test_array_operator[]
	rm -rf test_array_front
	rm -rf test_array_back
	rm -rf test_array_data
	rm -rf test_array_fill
	rm -rf test_array_swap
	rm -rf test_array_iterator
