all:
	mkdir output
	g++ -std=c++17 -I../ test_default_constructor.cpp -o ./output/test_default_constructor
	g++ -std=c++17 -I../ test_copy_constructor.cpp -o ./output/test_copy_constructor
        
clean:
	rm -rf ./output
