all:
	mkdir output
	g++ -std=c++11 -I../ test_default_constructor.cpp -o ./output/test_default_constructor
	g++ -std=c++11 -I../ test_copy_constructor.cpp -o ./output/test_copy_constructor
	g++ -std=c++11 -I../ test_front.cpp -o ./output/test_front
        
clean:
	rm -rf ./output
