all:
	mkdir output
	g++ -std=c++11 -I../ test_default_constructor.cpp -o ./output/test_default_constructor
	g++ -std=c++11 -I../ test_copy_constructor.cpp -o ./output/test_copy_constructor
	g++ -std=c++11 -I../ test_constructor_with_initializer_list.cpp -o ./output/test_constructor_with_initializer_list
	g++ -std=c++11 -I../ test_front.cpp -o ./output/test_front
	g++ -std=c++11 -I../ test_assignment_operator.cpp -o ./output/test_assignment_operator
        
clean:
	rm -rf ./output
