all:
	mkdir output
	g++ -std=c++11 -I../ test_default_constructor.cpp -o ./output/test_default_constructor
	g++ -std=c++11 -I../ test_pop_back.cpp -o ./output/test_pop_back
	g++ -std=c++11 -I../ test_swap.cpp -o ./output/test_swap
	g++ -std=c++11 -I../ test_clear.cpp -o ./output/test_clear
        
clean:
	rm -rf ./output
